apiVersion: v1
kind: ConfigMap
metadata:
  name: html-index
  namespace: html-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My OpenShift CRC HTML Pod</title>
    </head>
    <body style="text-align:center; margin-top:50px; font-family:sans-serif;">
        <h1>🚀 Welcome to My OpenShift CRC HTML Pod!</h1>
        <p>This is a sample HTML pod running in OpenShift CRC.</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-pod
  namespace: html-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-pod
  template:
    metadata:
      labels:
        app: html-pod
    spec:
      containers:
      - name: html-container
        image: quay.io/nginx/nginx-unprivileged:1.27
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: html-volume
        configMap:
          name: html-index
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
  namespace: html-demo
spec:
  selector:
    app: html-pod
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: html-route
  namespace: html-demo
spec:
  to:
    kind: Service
    name: html-service
  port:
    targetPort: http
